################## Project Specific Entries #######################
#
# These values override other definitions
#
# Project name

PROJECT=roach2_bsp
# module ID -> 32 bit hex (0xDEADCAFE == 3735931646)
BOARD_ID=3735931646
REV_MAJOR=2
REV_MINOR=3
RCS_UPTODATE=0
REV_RCS=0
# Pin Constraints
#PCFILE=constraints/roach2_rev0.ucf
PCFILE=constraints/roach2_rev2.ucf
# Enter your source files here space seperated
#      Note: no spaces in filenames

SRC=./modules/toplevel/hdl/toplevel.v \
    ./modules/infrastructure/hdl/infrastructure.v \
    ./modules/clk_gen/hdl/clk_gen.v \
		./modules/knight_rider/hdl/knight_rider.v \
		./modules/knight_rider/hdl/pwm_sm.v \
		./modules/epb_infrastructure/hdl/epb_infrastructure.v \
		./modules/epb_wb_bridge_reg/hdl/epb_wb_bridge_reg.v \
		./modules/wbs_arbiter/hdl/timeout.v \
		./modules/wbs_arbiter/hdl/wbs_arbiter.v \
		./modules/gpio_controller/hdl/gpio_controller.v \
		./modules/sys_block/hdl/sys_block.v \
		./modules/kat_adc/*/*.v \
		./include/parameters.v


# Module name of toplevel entity
TOPLEVEL_MODULE=toplevel
# Logic Device Part Number
PARTNUM=6vsx475t-ff1759-1

# Verilog Include Directory
VINC=include

GEN_DIR=gen
NETLIST_DIRS=./modules/kat_adc/iic_controller/netlist \
             ./modules/kat_adc/interface/netlist

NETLIST=./netlist
            
